From e600d12980ccb807ba1ca3fb6a4da1d0b89c02f6 Mon Sep 17 00:00:00 2001
From: Robert Collins <robertc@robertcollins.net>
Date: Wed, 1 Jul 2015 15:46:28 +1200
Subject: [PATCH] Fix tests with unittest2 1.1.0 and higher.

Change-Id: I4613d47852fbf901819f197f6e388ccaa717b53e
---
 testtools/tests/test_run.py | 1 +
 1 file changed, 1 insertion(+)

diff --git a/testtools/tests/test_run.py b/testtools/tests/test_run.py
index ead716b..433b6f8 100644
--- a/testtools/tests/test_run.py
+++ b/testtools/tests/test_run.py
@@ -201,6 +201,7 @@ def test_run_list_failed_import(self):
             run.main, ['prog', 'discover', '-l', broken.package.base, '*.py'], out)
         self.assertEqual(2, exc.args[0])
         self.assertThat(out.getvalue(), DocTestMatches("""\
+unittest2.loader._FailedTest.runexample
 Failed to import test module: runexample
 Traceback (most recent call last):
   File ".../loader.py", line ..., in _find_test_path
